name: CI/CD

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: musicabot:latest

      - name: vuln scan
        uses: aquasecurity/trivy-action@v0.28.0
        with:
          image_ref: musicabot:latest
          format: table
          ignore_unfixed: true
          severity: 'HIGH,CRITICAL'
          vuln-type: 'os,library'
          exit_code: '0'
