name: CI/CD
on:
  push:
    branches:
      - master
      - develop

jobs:
  ci:
    runs-on: ubuntu-latest
    if: (github.actor != 'semantic-release-bot' && (github.event.action != 'closed' && github.event.pull_request.merged != true)) 
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: echo github actor
        run: echo ${{ github.event.head_commit.author.username }}
