name: CI/CD
on:
  push:
    branches:
      - master
      - develop

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: echo github actor
        run: echo ${{ github.event.head_commit.author.username }}
