name: CI/CD

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: dockerize
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: musicabot:latest

      - name: vuln scan
        uses: dataswift/gha-trivy@v3.1.0
        with:
          image: musicabot:latest
          token: ${{ secrets.GITHUB_TOKEN }}
          severity: HIGH,CRITICAL
          vuln_type: os,library
