name: Single Manual Deploy
on:
  workflow_dispatch:
    inputs:
      country:
        description: 'Country to deploy'
        type: string
        required: true

jobs:

  release:
    uses: ./.github/workflows/semantic_release.yml
    with:
      country: ${{ inputs.country }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

